apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: openclaw
data:
  openclaw.json: |
    {
      "gateway": {
        "mode": "local",
        "bind": "lan",
        "auth": {
          "mode": "token"
        },
        "controlUi": {
          "dangerouslyAllowHostHeaderOriginFallback": true
        }
      }
    }
